[package]
name = "taurus-annotation"
version = "0.0.1"
authors = ["Pei Wang <wangpei10@baidu.com>"]
edition = "2018"

[lib]
test = false
doctest = false
plugin = true

[dependencies]
taurus-attributes = { path = "../attributes" }
